### ISSUE TITLE
import Errors

### ISSUE THREAD

**Issue by kiranmaya** [delta/dalal-street-android#158]
Getting import error 
![IMPORTeRROR](https://user-images.githubusercontent.com/3712631/83493472-73bbdb00-a4d2-11ea-95a3-af2b96da6318.png)

**Comment by ranaaditya** [comment]
> Getting import error
> ![IMPORTeRROR](https://user-images.githubusercontent.com/3712631/83493472-73bbdb00-a4d2-11ea-95a3-af2b96da6318.png)

@kiranmaya  you are getting these errors because **protobuf** is now a submodule, so clone it into your app before building.

for references how to use git submodules you can check [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

commit which make protobuf a submodule is here [commit](https://github.com/delta/dalal-street-android/commit/d6970111541346085e9f67e40af4b1e03ae28d92) 

And repo for protobuf is [here](https://github.com/delta/dalal-street-proto)
