### ISSUE TITLE
Replacing Koltin-synthetics with Jetpack's view binding

### ISSUE THREAD

**Issue by ranaaditya** [delta/dalal-street-android#159]
**Kotlin Android Extensions is deprecated, which means that using Kotlin synthetics for view binding is no longer supported !**

Need to Upgrade the app with [view binding](https://developer.android.com/topic/libraries/view-binding), **Migration** docs are available [**here**](https://developer.android.com/topic/libraries/view-binding/migration)

**NOTE: this going to be big edit and replace issue so need to be done with proper testing after each component**

**Comment by Sudhindra3000** [comment]
I ran into a problem while using ViewBinding. We are using multiple ExpandableTextView's in GettingStartedFragment and FaqFragment. Some views have same ids in these layout files beacause of [this:](https://github.com/Manabu-GT/ExpandableTextView#usage)
```The important thing to note is that the view Ids for TextView and ImageButton must be set to "@id/expandable_text" and "@id/expand_collapse" respectively for this library to work.```
But ViewBinding does not support same ids in the same layout file. So it is causing error while building the app. Setting different ids for different Textviews and ImageButtons that are inside ExpandableTextViews is obviously not an option. Because then ExpandableTextView will not work. I have tried to [ignore ViewBinding](https://developer.android.com/topic/libraries/view-binding#setup) in the above two layout files but it is causing the same error

**Comment by Sudhindra3000** [comment]
> I ran into a problem while using ViewBinding. We are using multiple ExpandableTextView's in GettingStartedFragment and FaqFragment. Some views have same ids in these layout files beacause of [this:](https://github.com/Manabu-GT/ExpandableTextView#usage)
> `The important thing to note is that the view Ids for TextView and ImageButton must be set to "@id/expandable_text" and "@id/expand_collapse" respectively for this library to work.`
> But ViewBinding does not support same ids in the same layout file. So it is causing error while building the app. Setting different ids for different Textviews and ImageButtons that are inside ExpandableTextViews is obviously not an option. Because then ExpandableTextView will not work. I have tried to [ignore ViewBinding](https://developer.android.com/topic/libraries/view-binding#setup) in the above two layout files but it is causing the same error

Got a solution for this. [Ignoring ViewBinding](https://developer.android.com/topic/libraries/view-binding#setup) for `fragment_getting_started.xml` and `fragment_faq.xml` actually works. The reason it didn't work before is because of Android Studio Caching. I did Invalidate Caches / Restart and then when i run the app there are no build errors. So i guess i have to leave `GettingStartedFragment` and `FaqFragment` while Migrating Kotlin Synthetics to ViewBinding

**Comment by ranaaditya** [comment]
This issue has been resolved with [this commit](https://github.com/delta/dalal-street-android/commit/23f9cf3c0f5ce05078de069d83dfdc0db47b5209), need to test the changes properly before  merging into main branch.

**Comment by ranaaditya** [comment]
This issue has been resolved with [this commit](https://github.com/delta/dalal-street-android/commit/5366cbd4ea29feb6e2c28d4736ca0292c59cbfe2) in main branch.

Thanks @Sudhindra3000 for your contribution :partying_face:
